# Chart.yaml
apiVersion: v2
name: go-app
version: 0.1.0
appVersion: 1.0.0
description: A Helm chart for deploying the Go application and MySQL database

maintainers:
  - name: Moaz Elmaaatwy
    email: moaz.elmaatawy@gmail.com
  